[agent]
name = "interface"
version = "0.0.1"

[options.OPENAI_API_KEY]
type = "string"
description = "OpenAI API Key"

[runtimes.executable]
command = ["bash", "./venv.sh", "./mcp_example_camel_interface.py"]